import React from 'react';
import { motion } from 'motion/react';
import { 
  X, 
  Check, 
  Minus, 
  TrendingUp, 
  Coins, 
  Scale, 
  Award, 
  Heart, 
  Bed, 
  ShowerHead, 
  Maximize2, 
  Calendar, 
  ShieldCheck, 
  Compass, 
  Sparkles, 
  Bookmark, 
  Trash2, 
  ExternalLink,
  FileDown,
  Leaf
} from 'lucide-react';
import { Property } from '../types';
import { jsPDF } from 'jspdf';
import EnergyRatingBadge from './EnergyRatingBadge';

interface PropertyComparisonOverlayProps {
  isOpen: boolean;
  onClose: () => void;
  comparedProperties: Property[];
  onRemove: (id: string, e?: React.MouseEvent) => void;
  onSelect: (p: Property) => void;
  lang: 'fr' | 'en' | 'sw';
}

export default function PropertyComparisonOverlay({
  isOpen,
  onClose,
  comparedProperties,
  onRemove,
  onSelect,
  lang
}: PropertyComparisonOverlayProps) {
  if (!isOpen) return null;

  // Local Dictionary for complete multi-language support (Extended for PDF export)
  const dict = {
    title: {
      fr: "Comparaison des Opportunités d'Investissement",
      en: "Investment Opportunity Comparison",
      sw: "Ulinganishi wa Fursa za Uwekezaji"
    },
    subtitle: {
      fr: "Analyse comparative approfondie des caractéristiques physiques et des rendements financiers",
      en: "In-depth side-by-side analysis of physical attributes and financial yields",
      sw: "Uchambuzi wa kina wa sifa za nyumba na mapato ya kifedha"
    },
    emptyTitle: {
      fr: "Aucune propriété sélectionnée",
      en: "No Properties Selected",
      sw: "Hakuna Mali Iliyochaguliwa"
    },
    emptyDesc: {
      fr: "Sélectionnez jusqu'à 3 propriétés depuis les fiches d'exploration immobilière pour démarrer la comparaison détaillée.",
      en: "Select up to 3 properties from the real estate listing cards to begin detailed comparison.",
      sw: "Chagua hadi mali 3 kutoka kadi za mali kuanza ulinganisho wa kina."
    },
    btnRemove: {
      fr: "Retirer",
      en: "Remove",
      sw: "Ondoa"
    },
    btnView: {
      fr: "Voir Fiche",
      en: "View Details",
      sw: "Angalia Mali"
    },
    bestFeature: {
      fr: "Meilleur",
      en: "Best",
      sw: "Bora zaidi"
    },
    btnExport: {
      fr: "Exporter en PDF",
      en: "Export PDF Report",
      sw: "Hamisha PDF"
    },
    pdfTitle: {
      fr: "Rapport de Comparaison d'Investissement - ImmoAI",
      en: "Investment Comparison Matrix - ImmoAI Africa",
      sw: "Ripoti ya Ulinganishi wa Uwekezaji - ImmoAI"
    },
    pdfFooter: {
      fr: "Généré par ImmoAI Africa - Moteur d'Analyse Économique",
      en: "Generated by ImmoAI Africa - Economic Asset Evaluator",
      sw: "Imetengenezwa na ImmoAI Africa - Mfumo wa Tathmini"
    },
    // Sections
    secGeneral: {
      fr: "Informations Générales",
      en: "General Information",
      sw: "Maelezo ya Jumla"
    },
    secSpecs: {
      fr: "Fiche Technique Physique",
      en: "Physical Specifications",
      sw: "Sifa za Kimaumbile"
    },
    secFinance: {
      fr: "Gains & Rentabilités Financières (IA)",
      en: "Financial Yields & Returns (AI Powered)",
      sw: "Mapato na Faida za Kifedha (IA)"
    },
    secAmenities: {
      fr: "Équipements & Confort",
      en: "Amenities & Comfort",
      sw: "Vistawishi na Faraja"
    },
    // Row Labels
    lblPrice: {
      fr: "Prix d'Acquisition",
      en: "Acquisition Price",
      sw: "Bei ya Ununuzi"
    },
    lblCategory: {
      fr: "Catégorie",
      en: "Category",
      sw: "Kundi"
    },
    lblLocation: {
      fr: "Emplacement / Ville",
      en: "Location / City",
      sw: "Mahali / Jiji"
    },
    lblArea: {
      fr: "Superficie Totale",
      en: "Total Area",
      sw: "Eneo Lote"
    },
    lblBedsBaths: {
      fr: "Chambres / Bains",
      en: "Beds / Baths",
      sw: "Vyumba / Bafu"
    },
    lblCondition: {
      fr: "État Général",
      en: "General Condition",
      sw: "Hali ya Nyumba"
    },
    lblView: {
      fr: "Panorama / Vue",
      en: "Panorama / View",
      sw: "Mtazamo / Mandhari"
    },
    lblYear: {
      fr: "Année de Construction",
      en: "Year Built",
      sw: "Mwaka wa Ujenzi"
    },
    lblEnergy: {
      fr: "Efficacité Énergétique (DPE)",
      en: "Energy Efficiency (DPE)",
      sw: "Ufanisi wa Nishati"
    },
    lblPriceSqm: {
      fr: "Coût au m²",
      en: "Cost per m²",
      sw: "Gharama kwa m²"
    },
    lblEstRent: {
      fr: "Loyer Mensuel Estimé",
      en: "Estimated Monthly Rent",
      sw: "Kodi ya Kila Mwezi Inayokadiriwa"
    },
    lblYield: {
      fr: "Rendement Brut de Location",
      en: "Gross Rental Yield",
      sw: "Faida ya Kodi Inayokadiriwa"
    },
    lblAiScore: {
      fr: "Score d'Opportunité IA",
      en: "AI Investment Score",
      sw: "Alama ya Uwekezaji wa IA"
    },
    lblAnalysis: {
      fr: "Observations de l'IA",
      en: "AI Analysis Insights",
      sw: "Uchunguzi wa IA"
    },
    // Amenities
    amPool: {
      fr: "Piscine Privée",
      en: "Private Pool",
      sw: "Bwawa la Kuogelea"
    },
    amGym: {
      fr: "Salle de Fitness",
      en: "Fitness Gym",
      sw: "Ukumbi wa Mazoezi"
    },
    amSecurity: {
      fr: "Sécurité Résidentielle 24/7",
      en: "24/7 Gate Security",
      sw: "Ulinzi wa Masaa 24"
    },
    amAc: {
      fr: "Climatisation Centrale",
      en: "Central AC System",
      sw: "Mfumo wa AC"
    },
    amSolar: {
      fr: "Source Solaire / Secours",
      en: "Solar Power / Backup Generator",
      sw: "Nishati ya Jua / Backup"
    },
    amWifi: {
      fr: "Fibre Internet Très Haut Débit",
      en: "High-Speed Fiber Wifi",
      sw: "Mtandao wa Kasi wa Fiber"
    }
  };

  const getTranslation = (key: keyof typeof dict) => {
    return dict[key][lang] || dict[key]['en'];
  };

  // Safe Dynamic Calculations for comparison rows
  const getRentEstimate = (p: Property) => {
    // Dynamic rent calculation: 7.5% gross yield baseline, adjusted for bedrooms (+0.5% per bed)
    const factor = 0.075 + (p.beds * 0.005);
    return Math.round((p.price * factor) / 12);
  };

  const getGrossYield = (p: Property) => {
    const rent = getRentEstimate(p);
    const annualRent = rent * 12;
    return Math.round((annualRent / p.price) * 1000) / 10;
  };

  const getAiScore = (p: Property) => {
    if (p.aiEstimate?.investment_score) return p.aiEstimate.investment_score;
    // Dynamic organic rating based on metrics
    let score = 7.3 + (p.beds * 0.2) + (p.baths * 0.1);
    if (p.condition === 'New') score += 0.8;
    if (p.condition === 'Excellent') score += 0.5;
    if (p.location.toLowerCase().includes('gombe') || p.location.toLowerCase().includes('zanzibar')) score += 0.4;
    return Math.min(10, Math.round(score * 10) / 10);
  };

  const getPricePerSqm = (p: Property) => {
    return Math.round(p.price / p.sqm);
  };

  const getAiReasoning = (p: Property) => {
    if (p.aiEstimate?.investment_reasoning) return p.aiEstimate.investment_reasoning;
    if (lang === 'fr') {
      return `Excellente valorisation estimée à ${p.location}. La classe d'actif ${p.category} présente un risque d'actif modéré et un taux de vacance locative bas de ~4.5%.`;
    } else if (lang === 'sw') {
      return `Ongezeko kubwa la thamani linatarajiwa ${p.location}. Kundi la ${p.category} lina nafasi ndogo sana ya kukosa wapangaji (~4.5%).`;
    } else {
      return `High potential for asset appreciation in ${p.location}. The ${p.category} inventory boasts strong liquidity with compressed vacancy metrics around ~4.5%.`;
    }
  };

  // Evaluation Metrics Helper: Find which index has the "best" value
  // Returns -1 if no clear winner or same
  const getBestIndex = (type: 'price' | 'aiScore' | 'sqm' | 'priceSqm' | 'yield') => {
    if (comparedProperties.length < 2) return -1;
    const values = comparedProperties.map(p => {
      if (type === 'price') return p.price;
      if (type === 'aiScore') return getAiScore(p);
      if (type === 'sqm') return p.sqm;
      if (type === 'priceSqm') return getPricePerSqm(p);
      if (type === 'yield') return getGrossYield(p);
      return 0;
    });

    if (type === 'price' || type === 'priceSqm') {
      // Best is lowest
      const min = Math.min(...values);
      // Double check if all values are equal
      if (values.every(v => v === min)) return -1;
      return values.indexOf(min);
    } else {
      // Best is highest
      const max = Math.max(...values);
      if (values.every(v => v === max)) return -1;
      return values.indexOf(max);
    }
  };

  const bestPriceIdx = getBestIndex('price');
  const bestAiScoreIdx = getBestIndex('aiScore');
  const bestSqmIdx = getBestIndex('sqm');
  const bestPriceSqmIdx = getBestIndex('priceSqm');
  const bestYieldIdx = getBestIndex('yield');

  const amenitiesList = [
    { label: getTranslation('amPool'), tag: 'pool' },
    { label: getTranslation('amGym'), tag: 'gym' },
    { label: getTranslation('amSecurity'), tag: 'security' },
    { label: getTranslation('amAc'), tag: 'ac' },
    { label: getTranslation('amSolar'), tag: 'solar' },
    { label: getTranslation('amWifi'), tag: 'wifi' }
  ];

  // Verify Amenity match
  const hasAmenity = (p: Property, keyWord: string) => {
    if (!p.amenities || !Array.isArray(p.amenities)) return false;
    const kw = keyWord.toLowerCase();
    return p.amenities.some(a => {
      const target = a.toLowerCase();
      return target.includes(kw) || 
             (kw === 'solar' && (target.includes('panneau') || target.includes('solaire') || target.includes('solar') || target.includes('generator') || target.includes('générateur'))) ||
             (kw === 'pool' && (target.includes('piscine') || target.includes('pool'))) ||
             (kw === 'gym' && (target.includes('gym') || target.includes('fitness') || target.includes('sport')));
    });
  };

  // PDF Export Engine
  const handleExportPDF = () => {
    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      // A4 metrics
      const startX = 10;
      const totalWidth = 190;
      const numProps = comparedProperties.length;
      
      // Page styling palette
      const primaryColor = [15, 23, 42]; // slate-900
      const secondaryColor = [71, 85, 105]; // slate-600
      const accentColor = [197, 160, 89]; // elegant gold
      const lightBg = [248, 250, 252]; // soft background
      const white = [255, 255, 255];
      const grayLine = [226, 232, 240];
      
      // 1. Draw top brand banner
      doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.rect(startX, 10, totalWidth, 18, 'F');
      
      // Title inside top banner
      doc.setTextColor(white[0], white[1], white[2]);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(13);
      doc.text(dict.pdfTitle[lang].toUpperCase(), startX + 5, 21);
      
      // Right premium label badges
      doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.rect(startX + totalWidth - 48, 14, 43, 10, 'F');
      
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.setFontSize(8);
      doc.setFont('Helvetica', 'bold');
      doc.text("IMMOAI ADVISORY", startX + totalWidth - 43, 20);

      // Subtitle below the banner with Date info
      doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(9);
      const generatedDate = new Date().toISOString().replace('T', ' ').substring(0, 16);
      doc.text(`${getTranslation('subtitle')}  |  Date: ${generatedDate}`, startX, 35);
      
      // Draw dynamic header outline line
      doc.setDrawColor(grayLine[0], grayLine[1], grayLine[2]);
      doc.setLineWidth(0.3);
      doc.line(startX, 38, startX + totalWidth, 38);

      if (numProps === 0) {
        doc.setFontSize(11);
        doc.text(dict.emptyTitle[lang], startX + 10, 50);
        doc.save(`ImmoAI_Comparison_${lang}.pdf`);
        return;
      }

      // Dynamic Grid Column spacing definitions
      const col0Width = 50;
      const remainingWidth = totalWidth - col0Width;
      const colWidth = remainingWidth / numProps;

      // 2. Draw Column Headers (Property summary cells)
      let currentY = 42;
      
      // Left header criteria helper box
      doc.setFillColor(241, 245, 249);
      doc.rect(startX, currentY, col0Width - 2, 24, 'F');
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.text(lang === 'fr' ? 'PROPRIÉTÉS SÉLECTIONNÉES' : lang === 'sw' ? 'MALI ZILIZOCHAGULIWA' : 'SELECTED ASSETS', startX + 3, currentY + 10);
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      doc.text(lang === 'fr' ? 'Comparatif de rendement' : lang === 'sw' ? 'Ripoti mbadala ya kodi' : 'Comparative yield matrix', startX + 3, currentY + 15);

      // Selected Property Cards
      comparedProperties.forEach((p, idx) => {
        const xVal = startX + col0Width + idx * colWidth;
        
        // Solid box backings to make it readable
        doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
        doc.rect(xVal, currentY, colWidth - 2, 24, 'F');
        doc.setDrawColor(grayLine[0], grayLine[1], grayLine[2]);
        doc.rect(xVal, currentY, colWidth - 2, 24, 'S');

        // Upper Category
        doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(7);
        doc.text(p.category.toUpperCase(), xVal + 3, currentY + 6);

        doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.setFontSize(8.5);
        // Shorten string based on space
        const titleCharLimit = Math.floor((colWidth - 6) * 1.5);
        const shortTitle = p.title.length > titleCharLimit ? p.title.substring(0, titleCharLimit - 3) + '...' : p.title;
        doc.text(shortTitle.toUpperCase(), xVal + 3, currentY + 11);

        doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
        doc.setFont('Helvetica', 'normal');
        doc.setFontSize(7.5);
        const shortLoc = p.location.length > titleCharLimit ? p.location.substring(0, titleCharLimit - 3) + '...' : p.location;
        doc.text(shortLoc, xVal + 3, currentY + 16);

        // Bold Price
        doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(10.5);
        doc.text(`$${p.price.toLocaleString()}`, xVal + 3, currentY + 21);
      });

      currentY += 28;

      // Tabular drawing abstraction helpers
      const drawPdfSectionHeader = (title: string, y: number) => {
        doc.setFillColor(241, 245, 249);
        doc.rect(startX, y, totalWidth, 6.5, 'F');
        doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.text(title.toUpperCase(), startX + 3, y + 4.5);
      };

      const drawPdfRow = (label: string, dataGetter: (p: Property, idx: number) => string, y: number) => {
        // Label header text
        doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(7.5);
        doc.text(label, startX + 3, y + 5);

        comparedProperties.forEach((p, idx) => {
          const xVal = startX + col0Width + idx * colWidth;
          doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
          doc.setFont('Helvetica', 'normal');
          doc.setFontSize(8);
          doc.text(dataGetter(p, idx), xVal + 3, y + 5);
        });

        // thin alignment line below row
        doc.setDrawColor(241, 245, 249);
        doc.setLineWidth(0.15);
        doc.line(startX, y + 7.5, startX + totalWidth, y + 7.5);
      };

      // --- SECTION 1: PHYSICAL SPECIFICATIONS ---
      drawPdfSectionHeader(getTranslation('secSpecs'), currentY);
      currentY += 6.5;

      drawPdfRow(getTranslation('lblArea'), (p, idx) => `${p.sqm} m² ${idx === bestSqmIdx ? '(*)' : ''}`, currentY);
      currentY += 7.5;

      drawPdfRow(getTranslation('lblBedsBaths'), (p) => `${p.beds} Beds / ${p.baths} Baths`, currentY);
      currentY += 7.5;

      drawPdfRow(getTranslation('lblCondition'), (p) => p.condition || "Excellent", currentY);
      currentY += 7.5;

      drawPdfRow(getTranslation('lblView'), (p) => p.viewType || "Ocean", currentY);
      currentY += 7.5;

      drawPdfRow(getTranslation('lblYear'), (p) => String(p.yearBuilt || 2022), currentY);
      currentY += 7.5;

      drawPdfRow(getTranslation('lblEnergy'), (p) => `Classe ${p.energyRating || (p.condition === 'New' ? 'A+' : p.condition === 'Excellent' ? 'A' : 'B+')}`, currentY);
      currentY += 10; // Extra transition margin

      // --- SECTION 2: METRICS & FINANCES ---
      drawPdfSectionHeader(getTranslation('secFinance'), currentY);
      currentY += 6.5;

      drawPdfRow(getTranslation('lblPriceSqm'), (p, idx) => `$${getPricePerSqm(p).toLocaleString()} / m² ${idx === bestPriceSqmIdx ? '(*)' : ''}`, currentY);
      currentY += 7.5;

      drawPdfRow(getTranslation('lblEstRent'), (p) => `$${getRentEstimate(p).toLocaleString()} / month`, currentY);
      currentY += 7.5;

      drawPdfRow(getTranslation('lblYield'), (p, idx) => `${getGrossYield(p)}% Yield ${idx === bestYieldIdx ? '(*)' : ''}`, currentY);
      currentY += 7.5;

      // Custom formatting for AI Rating
      drawPdfRow(getTranslation('lblAiScore'), (p, idx) => `${getAiScore(p)} / 10 ${idx === bestAiScoreIdx ? '(Top Rated ★)' : ''}`, currentY);
      currentY += 10;

      // --- SECTION 3: EQUIPEMENTS & CONFORT ---
      drawPdfSectionHeader(getTranslation('secAmenities'), currentY);
      currentY += 6.5;

      amenitiesList.forEach((amenity) => {
        drawPdfRow(amenity.label, (p) => hasAmenity(p, amenity.tag) ? (lang === 'fr' ? 'Oui' : lang === 'sw' ? 'Ndio' : 'Yes') : (lang === 'fr' ? 'Non' : lang === 'sw' ? 'Hapana' : 'No'), currentY);
        currentY += 7.5;
      });

      currentY += 2.5;

      // --- SECTION 4: STRATEGIC AI OUTLOOK ---
      const secTitleAI = lang === 'fr' ? "Analyse Comparative Stratégique de l'IA" : lang === 'sw' ? "Uchambuzi wa Kimkakati wa IA" : "AI Strategic Comparison Outlook";
      drawPdfSectionHeader(secTitleAI, currentY);
      currentY += 9.5;

      // Side-by-side outlined panels
      comparedProperties.forEach((p, idx) => {
        const xVal = startX + col0Width + idx * colWidth;
        
        // Backing
        doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
        doc.rect(xVal, currentY, colWidth - 2, 38, 'F');
        doc.setDrawColor(grayLine[0], grayLine[1], grayLine[2]);
        doc.rect(xVal, currentY, colWidth - 2, 38, 'S');

        // Header label mapping inside the box
        doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(7.5);
        const nameCharLimit = Math.floor((colWidth - 6) * 1.5);
        const shortName = p.title.length > nameCharLimit ? p.title.substring(0, nameCharLimit - 3) + '...' : p.title;
        doc.text(shortName.toUpperCase(), xVal + 2, currentY + 4.5);

        // Gold divider below custom box header
        doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
        doc.setLineWidth(0.2);
        doc.line(xVal + 2, currentY + 6, xVal + colWidth - 4, currentY + 6);

        // Strategic paragraphs
        doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
        doc.setFont('Helvetica', 'normal');
        doc.setFontSize(6.5);

        const textToRender = getAiReasoning(p);
        const splitLines = doc.splitTextToSize(textToRender, colWidth - 6);
        
        splitLines.slice(0, 7).forEach((line, lineIdx) => {
          doc.text(line, xVal + 2, currentY + 11 + lineIdx * 3.5);
        });
      });

      // Side title helper
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.text("IMMOAI\nADVICE", startX + 5, currentY + 15);
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(6.5);
      doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      doc.text(lang === 'fr' ? "Renseignements\nsystémiques\nd'acquisition." : lang === 'sw' ? "Uamuzi wa mambo\nya nyumba\nkwa usahihi." : "Systemic asset\nacquisition\nanalysis.", startX + 5, currentY + 23);

      // Footer
      currentY += 41;
      doc.setDrawColor(grayLine[0], grayLine[1], grayLine[2]);
      doc.setLineWidth(0.3);
      doc.line(startX, currentY, startX + totalWidth, currentY);

      doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      doc.setFontSize(7);
      doc.text(`${dict.pdfFooter[lang]} | (*) Indique la meilleure performance de sa classe d'actif`, startX, currentY + 4);
      doc.text("Confidential Investment Diligence Report. Generative insights synthesized securely on Cloud Run.", startX, currentY + 7.5);

      // Save PDF triggering download inside the user browser cleanly
      doc.save(`ImmoAI_Comparative_Evaluation_${lang}.pdf`);
    } catch (err) {
      console.error("Critical PDF compilation error:", err);
    }
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 md:p-6 select-none sm:select-text">
      {/* Backdrop */}
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
        className="absolute inset-0 bg-black/95 backdrop-blur-2xl animate-fade"
      />

      {/* Main Container */}
      <motion.div 
        initial={{ opacity: 0, scale: 0.96, y: 15 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.96, y: 15 }}
        className="relative w-full max-w-7xl h-[92vh] max-h-[92vh] bg-surface rounded-[36px] shadow-3xl border border-white/10 overflow-hidden flex flex-col z-10"
      >
        {/* Header toolbar */}
        <div className="p-6 md:p-8 border-b border-white/5 flex items-center justify-between bg-surface-elevated/20 shrink-0">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="p-1 px-2.5 rounded-full bg-brand/10 text-brand text-[9px] font-black uppercase tracking-wider inline-flex items-center gap-1">
                <Scale size={10} />
                Smart Matrix V1.2
              </span>
            </div>
            <h2 className="font-display text-2xl md:text-3xl font-black text-white uppercase tracking-tight">
              {getTranslation('title')}
            </h2>
            <p className="text-xs text-gray-400 font-sans tracking-wide mt-1">
              {getTranslation('subtitle')}
            </p>
          </div>

          <div className="flex items-center gap-3">
            {comparedProperties.length > 0 && (
              <button 
                type="button"
                onClick={handleExportPDF}
                className="p-3 px-5 bg-brand text-black hover:bg-white rounded-full font-black text-xs transition-with-duration tracking-wider inline-flex items-center gap-2 uppercase shadow-lg shadow-brand/10 cursor-pointer"
              >
                <FileDown size={14} className="stroke-[2.5]" />
                <span>{getTranslation('btnExport')}</span>
              </button>
            )}
            <button 
              type="button"
              onClick={onClose}
              className="p-3 bg-white/5 hover:bg-red-500/20 hover:text-red-400 rounded-full text-gray-400 transition-all border border-white/10 cursor-pointer"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Content Box */}
        {comparedProperties.length === 0 ? (
          <div className="flex-1 flex flex-col items-center justify-center p-8 text-center text-gray-500 max-w-md mx-auto space-y-4 animate-fade">
            <div className="p-6 rounded-[28px] bg-white/5 border border-white/10 text-gray-400 animate-pulse">
              <Scale size={42} className="stroke-[1.5]" />
            </div>
            <h3 className="text-white font-bold text-lg select-text">{getTranslation('emptyTitle')}</h3>
            <p className="text-sm leading-relaxed">{getTranslation('emptyDesc')}</p>
          </div>
        ) : (
          <div className="flex-1 overflow-y-auto overflow-x-auto p-4 md:p-8 space-y-8 no-scrollbar">
            <div className="min-w-[850px]">
              {/* Flex columns grid */}
              <div className="grid grid-cols-4 gap-6 items-stretch">
                {/* 1st Column: Side label guide */}
                <div className="col-span-1 flex flex-col justify-between py-2">
                  <div className="h-[210px] flex flex-col justify-end pb-4 pr-4">
                    <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest block mb-1">MÉTRIQUES DE COMPARAISON</span>
                    <p className="text-xs text-gray-400 leading-snug">Sélectionnez les meilleures structures d'actifs pour maximiser le cashflow net.</p>
                  </div>
                </div>

                {/* Selected Property Cards */}
                {comparedProperties.slice(0, 3).map((p, idx) => (
                  <div key={p.id} className="col-span-1 bg-surface-elevated/40 border border-white/10 rounded-[28px] p-4 flex flex-col justify-between h-[210px] group relative hover:border-white/20 transition-all shadow-xl">
                    <button 
                      type="button"
                      onClick={(e) => onRemove(p.id, e)}
                      aria-label="Remove asset"
                      className="absolute top-3 right-3 p-1.5 bg-black/60 backdrop-blur-md rounded-full text-gray-400 hover:text-red-400 hover:bg-black transition-all border border-white/10 z-10 cursor-pointer"
                    >
                      <Trash2 size={12} />
                    </button>

                    <div className="flex gap-3">
                      <div className="w-14 h-14 rounded-xl overflow-hidden shrink-0 border border-white/10 bg-black/40">
                        <img src={p.image} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" alt="" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <span className="text-[9px] font-black bg-white/10 text-white hover:bg-brand/20 hover:text-brand px-2 py-0.5 rounded-full inline-block tracking-wider mb-1">
                          {p.category}
                        </span>
                        <h4 className="font-bold text-white text-xs truncate uppercase tracking-tight block">
                          {p.title}
                        </h4>
                        <span className="text-[10px] text-gray-400 font-mono truncate block mt-0.5 animate-pulse">
                          {p.location}
                        </span>
                      </div>
                    </div>

                    <div className="mt-4 border-t border-white/5 pt-3">
                      <div className="flex items-baseline justify-between">
                        <span className="text-gray-400 text-[10px] font-mono">PRIX</span>
                        <span className={`text-lg font-black tracking-tight ${idx === bestPriceIdx ? 'text-brand' : 'text-white'}`}>
                          ${p.price.toLocaleString()}
                        </span>
                      </div>
                      {idx === bestPriceIdx && (
                        <span className="text-[8px] font-black bg-brand/10 text-brand px-2 py-0.5 rounded-full uppercase tracking-wider inline-block mt-1 animate-pulse">
                          ★ {getTranslation('bestFeature')} (Économique)
                        </span>
                      )}
                    </div>

                    <div className="mt-2 text-right">
                      <button 
                        type="button"
                        onClick={() => onSelect(p)}
                        className="text-[10px] font-black bg-brand text-black hover:bg-white px-3 py-1.5 rounded-lg inline-flex items-center gap-1 transition-all uppercase tracking-wider"
                      >
                        {getTranslation('btnView')}
                        <ExternalLink size={10} />
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              {/* Specification table lists */}
              <div className="space-y-6 mt-8">
                {/* physical specs */}
                <div className="border border-white/5 rounded-3xl bg-surface-elevated/10 overflow-hidden">
                  <div className="bg-white/5 px-6 py-4 border-b border-white/5 flex items-center justify-between">
                    <span className="text-xs font-black text-white uppercase tracking-wider flex items-center gap-2">
                      <Bed size={14} className="text-brand" />
                      {getTranslation('secSpecs')}
                    </span>
                  </div>

                  <div className="divide-y divide-white/5">
                    {/* area */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <Maximize2 size={12} className="text-gray-500" />
                        {getTranslation('lblArea')}
                      </div>
                      {comparedProperties.map((p, idx) => (
                        <div key={p.id} className="col-span-1 text-white font-bold text-sm tracking-tight flex items-center gap-2">
                          <span>{p.sqm} m²</span>
                          {idx === bestSqmIdx && (
                            <span className="text-[8px] font-black bg-green-500/10 text-green-400 px-1.5 py-0.5 rounded uppercase tracking-wider">
                              {getTranslation('bestFeature')}
                            </span>
                          )}
                        </div>
                      ))}
                    </div>

                    {/* beds */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <Bed size={12} className="text-gray-500" />
                        {getTranslation('lblBedsBaths')}
                      </div>
                      {comparedProperties.map(p => (
                        <div key={p.id} className="col-span-1 text-white text-sm font-semibold tracking-wide">
                          {p.beds} Beds / {p.baths} Baths
                        </div>
                      ))}
                    </div>

                    {/* condition */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <ShieldCheck size={12} className="text-gray-500" />
                        {getTranslation('lblCondition')}
                      </div>
                      {comparedProperties.map(p => (
                        <div key={p.id} className="col-span-1 text-white text-sm flex items-center gap-1.5 font-semibold">
                          <span className={`w-2 h-2 rounded-full ${
                            p.condition === 'New' ? 'bg-emerald-500' :
                            p.condition === 'Excellent' ? 'bg-blue-500' :
                            p.condition === 'Good' ? 'bg-amber-500' : 'bg-red-400'
                          }`} />
                          {p.condition || "Excellent"}
                        </div>
                      ))}
                    </div>

                    {/* panorama */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <Compass size={12} className="text-gray-500" />
                        {getTranslation('lblView')}
                      </div>
                      {comparedProperties.map(p => (
                        <div key={p.id} className="col-span-1 text-white text-sm font-semibold flex items-center gap-1 text-gray-300">
                          {p.viewType || "Ocean"}
                        </div>
                      ))}
                    </div>

                    {/* year */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <Calendar size={12} className="text-gray-500" />
                        {getTranslation('lblYear')}
                      </div>
                      {comparedProperties.map(p => (
                        <div key={p.id} className="col-span-1 text-white text-sm font-mono text-gray-300">
                          {p.yearBuilt || 2022}
                        </div>
                      ))}
                    </div>

                    {/* energy efficiency */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <Leaf size={12} className="text-emerald-500" />
                        {getTranslation('lblEnergy')}
                      </div>
                      {comparedProperties.map((p) => (
                        <div key={p.id} className="col-span-1 flex items-center gap-2">
                          <EnergyRatingBadge
                            rating={p.energyRating}
                            condition={p.condition}
                            energyKwh={p.energyKwh}
                            variant="pill"
                            lang={lang}
                          />
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* financial specs */}
                <div className="border border-white/5 rounded-3xl bg-surface-elevated/10 overflow-hidden">
                  <div className="bg-white/5 px-6 py-4 border-b border-white/5 flex items-center justify-between">
                    <span className="text-xs font-black text-white uppercase tracking-wider flex items-center gap-2">
                      <Coins size={14} className="text-brand animate-pulse" />
                      {getTranslation('secFinance')}
                    </span>
                    <span className="text-[9px] font-black bg-brand text-black px-2 py-0.5 rounded-full uppercase tracking-wider">
                      MOTEUR DE CALCUL IMMOAI
                    </span>
                  </div>

                  <div className="divide-y divide-white/5">
                    {/* per sqm cost */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <Coins size={12} className="text-gray-500" />
                        {getTranslation('lblPriceSqm')}
                      </div>
                      {comparedProperties.map((p, idx) => (
                        <div key={p.id} className="col-span-1 text-white text-sm font-mono flex items-center gap-1.5">
                          <span className={idx === bestPriceSqmIdx ? 'text-brand font-black' : 'font-bold'}>
                            ${getPricePerSqm(p).toLocaleString()} / m²
                          </span>
                          {idx === bestPriceSqmIdx && (
                            <span className="text-[8px] font-black bg-brand/10 text-brand px-1.5 py-0.5 rounded uppercase tracking-wider">
                              {getTranslation('bestFeature')}
                            </span>
                          )}
                        </div>
                      ))}
                    </div>

                    {/* Rent estimate */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <TrendingUp size={12} className="text-gray-500" />
                        {getTranslation('lblEstRent')}
                      </div>
                      {comparedProperties.map(p => (
                        <div key={p.id} className="col-span-1 text-emerald-400 font-bold text-sm">
                          ${getRentEstimate(p).toLocaleString()} / mois
                        </div>
                      ))}
                    </div>

                    {/* Gross yield */}
                    <div className="grid grid-cols-4 items-center px-6 py-4.5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <Scale size={12} className="text-gray-500" />
                        {getTranslation('lblYield')}
                      </div>
                      {comparedProperties.map((p, idx) => (
                        <div key={p.id} className="col-span-1 text-emerald-400 font-black text-sm flex items-center gap-2">
                          <span className="text-base text-white">{getGrossYield(p)}% ROI</span>
                          {idx === bestYieldIdx && (
                            <span className="text-[8px] font-black bg-emerald-500/10 text-green-400 px-1.5 py-0.5 rounded uppercase tracking-wider">
                              Rentabilité Max
                            </span>
                          )}
                        </div>
                      ))}
                    </div>

                    {/* score */}
                    <div className="grid grid-cols-4 items-center px-6 py-5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select">
                        <Award size={12} className="text-brand" />
                        {getTranslation('lblAiScore')}
                      </div>
                      {comparedProperties.map((p, idx) => {
                        const score = getAiScore(p);
                        return (
                          <div key={p.id} className="col-span-1 flex items-center gap-2.5">
                            <div className="relative flex items-center justify-center">
                              <div className={`w-9 h-9 rounded-full flex items-center justify-center font-black text-xs border ${
                                score >= 8.5 ? 'bg-brand/10 border-brand text-brand shadow-lg shadow-brand/10' : 'bg-white/5 border-white/10 text-white'
                              }`}>
                                {score}
                              </div>
                            </div>
                            {idx === bestAiScoreIdx && (
                              <span className="text-[8px] font-black bg-brand/20 text-brand px-2 py-0.5 rounded-full uppercase tracking-wider">
                                Recommandé IA ★
                              </span>
                            )}
                          </div>
                        );
                      })}
                    </div>

                    {/* observations */}
                    <div className="grid grid-cols-4 items-start px-6 py-5 group hover:bg-white/[0.01] transition-all">
                      <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] flex items-center gap-1.5 label-no-select pt-0.5">
                        <Sparkles size={12} className="text-brand" />
                        {getTranslation('lblAnalysis')}
                      </div>
                      {comparedProperties.map(p => (
                        <div key={p.id} className="col-span-1 text-gray-300 text-[11px] leading-relaxed pr-2 italic">
                          "{getAiReasoning(p)}"
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* amenities column items */}
                <div className="border border-white/5 rounded-3xl bg-surface-elevated/10 overflow-hidden">
                  <div className="bg-white/5 px-6 py-4 border-b border-white/5">
                    <span className="text-xs font-black text-white uppercase tracking-wider flex items-center gap-2">
                      <Sparkles className="text-brand" size={14} />
                      {getTranslation('secAmenities')}
                    </span>
                  </div>

                  <div className="divide-y divide-white/5">
                    {amenitiesList.map((row) => (
                      <div key={row.tag} className="grid grid-cols-4 items-center px-6 py-4 group hover:bg-white/[0.01] transition-all">
                        <div className="col-span-1 text-xs font-bold text-gray-400 uppercase tracking-widest text-[10px] label-no-select">
                          {row.label}
                        </div>
                        {comparedProperties.map(p => {
                          const hasAm = hasAmenity(p, row.tag);
                          return (
                            <div key={p.id} className="col-span-1 flex items-center">
                              {hasAm ? (
                                <div className="text-brand flex items-center gap-1 bg-brand/10 p-1.5 px-3 rounded-lg border border-brand/20">
                                  <Check size={12} className="stroke-[3]" />
                                  <span className="text-[10px] font-bold uppercase tracking-wider">Oui</span>
                                </div>
                              ) : (
                                <div className="text-gray-600 flex items-center gap-1 bg-white/5 p-1.5 px-3 rounded-lg">
                                  <Minus size={12} />
                                  <span className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Non</span>
                                </div>
                              )}
                            </div>
                          );
                        })}
                      </div>
                    ))}
                  </div>
                </div>

              </div>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
}
